# Generated by Django 3.2.5 on 2021-08-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_shippingaddress_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
