# Generated by Django 3.2.5 on 2021-08-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.BooleanField(default=False),
        ),
    ]
